In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB,GaussianNB
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier,export_graphviz
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings('ignore')

In [5]:
mushroom=pd.read_csv('mushroom_data.csv')
mushroom.columns=['class','cap-shape','cap-surface','cap-color','bruises','odor','gill-attachment','gill-spacing','gill-size','gill-color','stalk-shape','stalk-root','stalk-surface-above-ring',' stalk-surface-below-ring','stalk-color-above-ring','stalk-color-below-ring','veil-type','veil-color','ring-number',' ring-type','spore-print-color','population','habitat']
mushroom.head()

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0     e         x           s         y       t    a               f   
1     e         b           s         w       t    l               f   
2     p         x           y         w       t    p               f   
3     e         x           s         g       f    n               f   
4     e         x           y         y       t    a               f   

  gill-spacing gill-size gill-color  ...  stalk-surface-below-ring  \
0            c         b          k  ...                         s   
1            c         b          n  ...                         s   
2            c         n          n  ...                         s   
3            w         b          k  ...                         s   
4            c         b          n  ...                         s   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  ring-number  ring-type spore-print-color population habitat  
0           o          p                 n          n       g  
1           o          p                 n          n       m  
2           o          p                 k          s       u  
3           o          e                 n          a       g  
4           o          p                 k          n       g  

[5 rows x 23 columns]

In [6]:
mushroom.tail()

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
8118     e         k           s         n       f    n               a   
8119     e         x           s         n       f    n               a   
8120     e         f           s         n       f    n               a   
8121     p         k           y         n       f    y               f   
8122     e         x           s         n       f    n               a   

     gill-spacing gill-size gill-color  ...  stalk-surface-below-ring  \
8118            c         b          y  ...                         s   
8119            c         b          y  ...                         s   
8120            c         b          n  ...                         s   
8121            c         n          b  ...                         k   
8122            c         b          y  ...                         s   

     stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
8118                      o                      o         p          o   
8119                      o                      o         p          n   
8120                      o                      o         p          o   
8121                      w                      w         p          w   
8122                      o                      o         p          o   

     ring-number  ring-type spore-print-color population habitat  
8118           o          p                 b          c       l  
8119           o          p                 b          v       l  
8120           o          p                 b          c       l  
8121           o          e                 w          v       l  
8122           o          p                 o          c       l  

[5 rows x 23 columns]

In [7]:
df=pd.DataFrame(data=mushroom)

In [8]:
df.head()

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0     e         x           s         y       t    a               f   
1     e         b           s         w       t    l               f   
2     p         x           y         w       t    p               f   
3     e         x           s         g       f    n               f   
4     e         x           y         y       t    a               f   

  gill-spacing gill-size gill-color  ...  stalk-surface-below-ring  \
0            c         b          k  ...                         s   
1            c         b          n  ...                         s   
2            c         n          n  ...                         s   
3            w         b          k  ...                         s   
4            c         b          n  ...                         s   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  ring-number  ring-type spore-print-color population habitat  
0           o          p                 n          n       g  
1           o          p                 n          n       m  
2           o          p                 k          s       u  
3           o          e                 n          a       g  
4           o          p                 k          n       g  

[5 rows x 23 columns]

In [9]:
df.tail(10)

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
8113     p         f           y         c       f    m               a   
8114     e         x           s         n       f    n               a   
8115     p         k           y         n       f    s               f   
8116     p         k           s         e       f    y               f   
8117     p         k           y         n       f    f               f   
8118     e         k           s         n       f    n               a   
8119     e         x           s         n       f    n               a   
8120     e         f           s         n       f    n               a   
8121     p         k           y         n       f    y               f   
8122     e         x           s         n       f    n               a   

     gill-spacing gill-size gill-color  ...  stalk-surface-below-ring  \
8113            c         b          y  ...                         y   
8114            c         b          y  ...                         s   
8115            c         n          b  ...                         k   
8116            c         n          b  ...                         s   
8117            c         n          b  ...                         s   
8118            c         b          y  ...                         s   
8119            c         b          y  ...                         s   
8120            c         b          n  ...                         s   
8121            c         n          b  ...                         k   
8122            c         b          y  ...                         s   

     stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
8113                      c                      c         p          w   
8114                      o                      o         p          o   
8115                      p                      w         p          w   
8116                      p                      w         p          w   
8117                      p                      w         p          w   
8118                      o                      o         p          o   
8119                      o                      o         p          n   
8120                      o                      o         p          o   
8121                      w                      w         p          w   
8122                      o                      o         p          o   

     ring-number  ring-type spore-print-color population habitat  
8113           n          n                 w          c       d  
8114           o          p                 o          v       l  
8115           o          e                 w          v       l  
8116           o          e                 w          v       d  
8117           o          e                 w          v       d  
8118           o          p                 b          c       l  
8119           o          p                 b          v       l  
8120           o          p                 b          c       l  
8121           o          e                 w          v       l  
8122           o          p                 o          c       l  

[10 rows x 23 columns]

In [10]:
df.describe()

class cap-shape cap-surface cap-color bruises  odor gill-attachment  \
count   8123      8123        8123      8123    8123  8123            8123   
unique     2         6           4        10       2     9               2   
top        e         x           y         n       f     n               f   
freq    4208      3655        3244      2283    4748  3528            7913   

       gill-spacing gill-size gill-color  ...  stalk-surface-below-ring  \
count          8123      8123       8123  ...                      8123   
unique            2         2         12  ...                         4   
top               c         b          b  ...                         s   
freq           6811      5612       1728  ...                      4935   

       stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
count                    8123                   8123      8123       8123   
unique                      9                      9         1          4   
top                         w                      w         p          w   
freq                     4463                   4383      8123       7923   

       ring-number  ring-type spore-print-color population habitat  
count         8123       8123              8123       8123    8123  
unique           3          5                 9          6       7  
top              o          p                 w          v       d  
freq          7487       3967              2388       4040    3148  

[4 rows x 23 columns]

In [11]:
x=df.iloc[:,0:-1]
x.shape

(8123, 22)

In [12]:
y=df.iloc[:,-1]

In [13]:
y

0       g
1       m
2       u
3       g
4       g
       ..
8118    l
8119    l
8120    l
8121    l
8122    l
Name: habitat, Length: 8123, dtype: object

In [14]:
from sklearn.preprocessing import OneHotEncoder
on=OneHotEncoder()
X=df.drop(columns='class')

X = on.fit_transform(X)

y = df['class'].replace({'p':0, 'e':1})

print('Feature matrix size:',X.shape)
print('Target vector size:',len(y))


Feature matrix size: (8123, 117)
Target vector size: 8123


In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size=.2, stratify=y)

print('Training feature matrix size:',X_train.shape)
print('Training target vector size:',y_train.shape)
print('Test feature matrix size:',X_test.shape)
print('Test target vector size:',y_test.shape)

Training feature matrix size: (6498, 117)
Training target vector size: (6498,)
Test feature matrix size: (1625, 117)
Test target vector size: (1625,)


In [16]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8123 entries, 0 to 8122
Data columns (total 23 columns):
class                        8123 non-null object
cap-shape                    8123 non-null object
cap-surface                  8123 non-null object
cap-color                    8123 non-null object
bruises                      8123 non-null object
odor                         8123 non-null object
gill-attachment              8123 non-null object
gill-spacing                 8123 non-null object
gill-size                    8123 non-null object
gill-color                   8123 non-null object
stalk-shape                  8123 non-null object
stalk-root                   8123 non-null object
stalk-surface-above-ring     8123 non-null object
 stalk-surface-below-ring    8123 non-null object
stalk-color-above-ring       8123 non-null object
stalk-color-below-ring       8123 non-null object
veil-type                    8123 non-null object
veil-color                   8123 non-null 

In [17]:
df.isnull().sum()

class                        0
cap-shape                    0
cap-surface                  0
cap-color                    0
bruises                      0
odor                         0
gill-attachment              0
gill-spacing                 0
gill-size                    0
gill-color                   0
stalk-shape                  0
stalk-root                   0
stalk-surface-above-ring     0
 stalk-surface-below-ring    0
stalk-color-above-ring       0
stalk-color-below-ring       0
veil-type                    0
veil-color                   0
ring-number                  0
 ring-type                   0
spore-print-color            0
population                   0
habitat                      0
dtype: int64

In [18]:
df=df.replace('?',np.NaN)

In [19]:
print(df.isna().sum())

class                           0
cap-shape                       0
cap-surface                     0
cap-color                       0
bruises                         0
odor                            0
gill-attachment                 0
gill-spacing                    0
gill-size                       0
gill-color                      0
stalk-shape                     0
stalk-root                   2480
stalk-surface-above-ring        0
 stalk-surface-below-ring       0
stalk-color-above-ring          0
stalk-color-below-ring          0
veil-type                       0
veil-color                      0
ring-number                     0
 ring-type                      0
spore-print-color               0
population                      0
habitat                         0
dtype: int64


In [20]:
print(df.dtypes)

class                        object
cap-shape                    object
cap-surface                  object
cap-color                    object
bruises                      object
odor                         object
gill-attachment              object
gill-spacing                 object
gill-size                    object
gill-color                   object
stalk-shape                  object
stalk-root                   object
stalk-surface-above-ring     object
 stalk-surface-below-ring    object
stalk-color-above-ring       object
stalk-color-below-ring       object
veil-type                    object
veil-color                   object
ring-number                  object
 ring-type                   object
spore-print-color            object
population                   object
habitat                      object
dtype: object


In [21]:
df.shape

(8123, 23)

In [22]:
df.columns

Index(['class', 'cap-shape', 'cap-surface', 'cap-color', 'bruises', 'odor',
       'gill-attachment', 'gill-spacing', 'gill-size', 'gill-color',
       'stalk-shape', 'stalk-root', 'stalk-surface-above-ring',
       ' stalk-surface-below-ring', 'stalk-color-above-ring',
       'stalk-color-below-ring', 'veil-type', 'veil-color', 'ring-number',
       ' ring-type', 'spore-print-color', 'population', 'habitat'],
      dtype='object')

In [23]:
df['stalk-root']=df['stalk-root'].replace(np.NaN,'m')

In [24]:
df['class'].value_counts(normalize=True)

e    0.518035
p    0.481965
Name: class, dtype: float64

In [25]:
print(df['stalk-root'].value_counts())

b    3776
m    2480
e    1119
c     556
r     192
Name: stalk-root, dtype: int64


In [26]:
majority_class = y_train.mode()[0]
baseline_predictions = [majority_class] * len(y_train)

In [27]:
majority_class_accuracy=accuracy_score(baseline_predictions,y_train)
print(majority_class_accuracy)

0.518005540166205


In [28]:
dtc=DecisionTreeClassifier()
dtc.fit(X_train,y_train)
preddtc=dtc.predict(X_test)
print(accuracy_score(y_test,preddtc))
print(confusion_matrix(y_test,preddtc))
print(classification_report(y_test,preddtc))

1.0
[[783   0]
 [  0 842]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       783
           1       1.00      1.00      1.00       842

    accuracy                           1.00      1625
   macro avg       1.00      1.00      1.00      1625
weighted avg       1.00      1.00      1.00      1625



In [29]:
mnb=MultinomialNB()
mnb.fit(X_train,y_train)
predmnb=mnb.predict(X_test)
print(accuracy_score(y_test,predmnb))
print(confusion_matrix(y_test,predmnb))
print(classification_report(y_test,predmnb))

0.9692307692307692
[[736  47]
 [  3 839]]
              precision    recall  f1-score   support

           0       1.00      0.94      0.97       783
           1       0.95      1.00      0.97       842

    accuracy                           0.97      1625
   macro avg       0.97      0.97      0.97      1625
weighted avg       0.97      0.97      0.97      1625



In [30]:
svc=SVC()
svc.fit(X_train,y_train)
predsvc=mnb.predict(X_test)
print(accuracy_score(y_test,predsvc))
print(confusion_matrix(y_test,predsvc))
print(classification_report(y_test,predsvc))

0.9692307692307692
[[736  47]
 [  3 839]]
              precision    recall  f1-score   support

           0       1.00      0.94      0.97       783
           1       0.95      1.00      0.97       842

    accuracy                           0.97      1625
   macro avg       0.97      0.97      0.97      1625
weighted avg       0.97      0.97      0.97      1625



In [31]:
lg=LogisticRegression()
lg.fit(X_train,y_train)
predlg=mnb.predict(X_test)
print(accuracy_score(y_test,predlg))
print(confusion_matrix(y_test,predlg))
print(classification_report(y_test,predlg))

0.9692307692307692
[[736  47]
 [  3 839]]
              precision    recall  f1-score   support

           0       1.00      0.94      0.97       783
           1       0.95      1.00      0.97       842

    accuracy                           0.97      1625
   macro avg       0.97      0.97      0.97      1625
weighted avg       0.97      0.97      0.97      1625



In [32]:
model=[LogisticRegression(),SVC(),MultinomialNB(),DecisionTreeClassifier()]

In [33]:
for m in model:
    m.fit(X_train,y_train)
    m.score(X_train,y_train)
    predm=m.predict(X_test)
    print('Actual score of',m,'is')
    print(accuracy_score(y_test,predm))
    print(confusion_matrix(y_test,predm))
    print(classification_report(y_test,predm))

Actual score of LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False) is
1.0
[[783   0]
 [  0 842]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       783
           1       1.00      1.00      1.00       842

    accuracy                           1.00      1625
   macro avg       1.00      1.00      1.00      1625
weighted avg       1.00      1.00      1.00      1625

Actual score of SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False) is
0.9993846153846154
[[782   1]
 [  0 842]]

In [34]:
from sklearn.ensemble import RandomForestRegressor

In [35]:
rf=RandomForestRegressor(n_estimators=200,random_state=45)
rf.fit(X_train,y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=200,
                      n_jobs=None, oob_score=False, random_state=45, verbose=0,
                      warm_start=False)

In [38]:
rf.score(X_train,y_train)
predrf=rf.predict(X_test)

In [39]:
predrf

array([1., 1., 0., ..., 0., 0., 1.])

In [41]:
from sklearn.externals import joblib

#save the model as pickle in file
joblib.dump(dtc,'mushroomfile.obj')

['mushroomfile.obj']